force-app/main/default/objects/Pipeline__c/Pipeline__c.object-meta.xml
<CustomObject>
    <label>Pipeline</label>
    <nameField>
        <label>Pipeline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipeline</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PipelineFilter__c/PipelineFilter__c.object-meta.xml
<CustomObject>
    <label>PipelineFilter</label>
    <nameField>
        <label>PipelineFilter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PipelineFilter</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PipelineFilter__c/fields/Pipeline__c.field-meta.xml
<CustomField>
    <fullName>Pipeline__c</fullName>
    <label>Pipeline</label>
    <referenceTo>Pipeline__c</referenceTo>
    <relationshipLabel>PipelineFilter</relationshipLabel>
    <relationshipName>WhipsLinks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PipelineFactory.cls
public class PipelineFactory {
    
    public static Pipeline createPipeline(Pipeline__c pipelineObj){
        
        Pipeline pipelineInstance = new Pipeline();
        
        for (PipelineFilter__c PipelineFilter : [SELECT 
                                                 	P.Id, 
                                                 	P.Name 
                                                 FROM PipelineFilter__c AS P 
                                                 WHERE P.Pipeline__c  = :pipelineObj.id 
                                                 	AND P.Active__c = True
                                                ]
            ){
		
            Type t = Type.forName(PipelineFilter.Name);
            FilterAbstract filter = (FilterAbstract)t.newInstance();
                
 			System.debug('Redy to add filter '+ filter);
           	pipelineInstance.addFilter(filter);
        }      
           
        System.debug('Returning from createPipeline()');
		return pipelineInstance;
              
        
    } 

}