force-app/main/default/objects/UploadQueue__c/UploadQueue__c.object-meta.xml
<CustomObject>
    <label>UploadQueue</label>
    <nameField>
        <label>Upload Queue record</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UploadQueue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UploadQueue__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>10000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/UploadQueue__c/fields/ObjectId__c.field-meta.xml
<CustomField>
    <fullName>ObjectId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>ObjectId</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_committed_changes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UploadQueue__c/fields/ObjectType__c.field-meta.xml
<CustomField>
    <fullName>ObjectType__c</fullName>
    <label>ObjectType</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/UploadQueue__c/fields/Recipient__c.field-meta.xml
<CustomField>
    <fullName>Recipient__c</fullName>
    <label>Recipient</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Eraser.cls
public class Eraser extends FilterAbstract{
    
    public override void setup(MessageStruct Message){}

    public override void process(MessageStruct Message){
        
        delete Message.GetChangeList();
        
 
        
        List<UploadQueue__c> ChangeList = [SELECT ObjectId__c, ObjectType__c, Message__c, Recipient__c, TimeStamp__c FROM UploadQueue__c ORDER BY TimeStamp__c];
       
        system.debug(ChangeList.size());
       	
        this.proceed(Message);
    }

}