force-app/main/default/objects/UploadQueue__c/UploadQueue__c.object-meta.xml
<CustomObject>
    <label>UploadQueue</label>
    <nameField>
        <label>Upload Queue record</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UploadQueue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UploadQueue__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>10000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/Composer.cls
public class Composer extends FilterAbstract{
    
    public override void setup(MessageStruct Message){}

    public override void process(MessageStruct Message){
              
        List<String> MessageList = new List<String>{};

        for (UploadQueue__c UploadQueueRecord : Message.GetChangeList()) {
        
            MessageList.add((String)UploadQueueRecord.Message__c);

        }
       
 		Message.PutMessage(JSON.serialize(MessageList));
         
        this.proceed(Message);
   }

}