force-app/main/default/objects/UploadQueue__c/UploadQueue__c.object-meta.xml
<CustomObject>
    <label>UploadQueue</label>
    <nameField>
        <label>Upload Queue record</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UploadQueue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UploadQueue__c/fields/ObjectId__c.field-meta.xml
<CustomField>
    <fullName>ObjectId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>ObjectId</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_committed_changes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UploadQueue__c/fields/ObjectType__c.field-meta.xml
<CustomField>
    <fullName>ObjectType__c</fullName>
    <label>ObjectType</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/TestCreateUploadQueueRecord.cls
@isTest
public class TestCreateUploadQueueRecord {

    @isTest
    static void TestDeleteAccountWithOneOpportunity(){
        
        //arrange
        Account acct = new Account(Name='Test Account');
        
        //act
		Test.startTest();
       
        Database.SaveResult result = Database.insert(acct);
        
		Test.stopTest();
        
        //assert
        System.assert(result.isSuccess());
        
        List<UploadQueue__c> QueryList = [SELECT 
                                              ObjectId__c, 
                                              ObjectType__c 
                                          FROM 
                                              UploadQueue__c 
                                          WHERE 
                                              ObjectId__c = :acct.id];
              
        System.assert(QueryList.size()==1);
        System.assert(QueryList[0].ObjectType__c==((SObject)acct).getSObjectType().getDescribe().getName()+'');
      
   }

}