force-app/main/default/objects/AccountQueue__c/AccountQueue__c.object-meta.xml
<CustomObject>
    <label>AccountQueue</label>
    <nameField>
        <label>Account Queue</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AccountQueue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountQueue__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Object</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_committed_changes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountQueue__c/fields/TimeStamp__c.field-meta.xml
<CustomField>
    <fullName>TimeStamp__c</fullName>
    <label>TimeStamp</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Getter.cls
public class Getter extends FilterAbstract{
    
    
    public override void setup(MessageStruct Message){}

    public override void process(MessageStruct Message){
            
        List<sObject> ChangeList = [SELECT Object__c, Message__c, Recipient__c, TimeStamp__c FROM AccountQueue__c ORDER BY TimeStamp__c];
    
        system.debug(ChangeList);
        
        this.proceed(Message);
    }
        
}